### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by 5high** [wzpan/ReSpeaker-Switcher#1]
pi@raspberrypi:~/ReSpeaker-Switcher $ python switcher.py 
Traceback (most recent call last):
  File "switcher.py", line 5, in <module>
    import alsaaudio
ImportError: No module named alsaaudio

**Comment by wzpan** [comment]
先安装依赖：

``` sh
pip install -r requirements.txt
```

**Comment by 5high** [comment]
依赖都装了，还是这样提示错误

pi@raspberrypi:~/ReSpeaker-Switcher $ python switcher.py
Traceback (most recent call last):
  File "switcher.py", line 5, in <module>
    import alsaaudio
ImportError: No module named alsaaudio
pi@raspberrypi:~/ReSpeaker-Switcher $ pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyalsaaudio in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (0.8.4)

**Comment by wzpan** [comment]
请试试启动一个 Python interactive shell：

``` shell
$ python
Python 2.7.16 (default, Mar  4 2019, 09:01:38) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

然后在里头输入 `import alsaaudio` 看看能否正常 import 还是报错。如果报错，那就是还是没装好。你的 pip 和 python 可能是指向了不同的版本。

**Comment by 5high** [comment]
现在这样了

pi@raspberrypi:~/ReSpeaker-Switcher $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~/ReSpeaker-Switcher $ python switcher.py 
error: can't find capture devices

**Comment by wzpan** [comment]
找不到你的录音设备。能正常录音吗？

试试终端中执行 `amixer` ，看看有没有  capture 设备。

**Comment by 5high** [comment]
有的，悟空所有功能正常

潘伟洲 <notifications@github.com> 于 2019年4月11日周四 16:18写道：

**Comment by wzpan** [comment]
那可能 respeaker 已经不支持这种方式控制麦克风了
